---
- name: Set GPU Operator flags for systems with preinstalled NVIDIA software (DGX, etc).
  set_fact:
    gpu_operator_enable_driver: false
    gpu_operator_enable_toolkit: true
  when: gpu_operator_preinstalled_nvidia_software

- name: deploy nvidia gpu operator to kubernetes
  include_tasks: k8s.yml
  when: not gpu_operator_nvaie_enable

- name: deploy nvidia gpu operator to nvidia ai enterprise
  include_tasks: nvaie.yml
  when: gpu_operator_nvaie_enable

