---
- name: Starting diagnostics step
  debug:
    msg: "Starting now"

- name: Check firmware
  include_tasks: check-firmware.yml
  ignore_errors: true

- name: Get health
  include_tasks: get-health.yml
  ignore_errors: true

- name: Get IB
  include_tasks: get-ib.yml
  ignore_errors: true
