---
- name: gather os specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - files:
      - "{{ ansible_distribution|lower }}.yml"
      - "{{ ansible_os_family|lower }}.yml"
      paths:
      - ../vars
      skip: true
  tags: vars

- name: Setup Open OnDemand server
  include_tasks: server.yml
  when: ood_is_server

- name: Setup Open OnDemand client
  include_tasks: client.yml
  when: ood_is_client

- name: Setup linuxhost adapter
  include_tasks: linuxhost-adapter.yml
  when: ood_is_server and ood_install_linuxhost_adapter
