---
- name: Install NVIDIA driver on GPU servers
  import_playbook: ../nvidia-software/nvidia-driver.yml

- name: Install NVIDIA container runtime on GPU servers
  import_playbook: nvidia-docker.yml
  vars:
    nvidia_docker_skip_docker_reload: true

- name: Install Lmod
  import_playbook: ../slurm-cluster/lmod.yml

- hosts: all
  become: yes
  tasks:
    - name: install rootless docker
      include_role:
        name: docker-rootless
