---
# Ensure Docker is installed and configured
- name: Install docker
  import_playbook: docker.yml

# Log into Docker registries
- hosts: "{{ hostlist | default('all') }}"
  become: yes
  roles:
  - docker-login
